version: 2

aliases:
  - &set-working-directory
    working_directory: /home/circleci/project

jobs:
  build:
    <<: *set-working-directory
    docker:
      - image: circleci/python:2.7-node
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          key: npm-packages-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Get firebase credentials
          command: aws s3 cp "s3://bridge-projects-firebase/bridgebot-firebase.json" "secrets.json"
      - run:
          name: Install Serverless CLI and plugins
          command: |
            sudo npm i -g serverless
            serverless plugin install --name serverless-offline
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          name: Save NPM Package Cache
          key: npm-packages-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules/
      - run:
          name: Deploy with serverless
          command: serverless deploy -v
workflows:
  version: 2
  test_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
